#!/usr/bin/env python
ERROR_SUCCESS = 0
ERROR_FILE_NOT_FOUND = 2
ERROR_BAD_ENVIRONMENT = 9
ERROR_BAD_FORMAT = 11
ERROR_NO_MORE_FILES = 18
ERROR_BAD_COMMAND = 22
ERROR_READ_FAULT = 30
ERROR_INVALID_PARAMETER=87
ERROR_PROC_NOT_FOUND = 127
ERROR_BAD_ARGUMENTS  = 160
ERROR_BUSY = 170
ERROR_ALREADY_EXISTS = 183
ERROR_BAD_PIPE = 230
ERROR_FAIL_SHUTDOWN = 351
ERROR_FAIL_RESTART = 352

